import type { List, Task, UrlScheme } from '../types/models';

export const mockLists: List[] = [
  { id: 'list_today', name: '所有任务', icon: '📋' },
  { id: 'list_work', name: '工作', icon: '💼' },
  { id: 'list_life', name: '生活', icon: '🏡' },
];

export const mockSchemes: UrlScheme[] = [
  {
    id: 'scheme_macos_sms',
    name: 'macos-短信',
    icon: '💬',
    template: 'sms://{param}',
    paramType: 'number',
  },
  {
    id: 'scheme_macos_tel',
    name: 'macos-电话',
    icon: '📞',
    template: 'tel://{param}',
    paramType: 'number',
  },
  {
    id: 'scheme_macos_message',
    name: 'macos-邮件',
    icon: '📨',
    template: 'message://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_shoebox',
    name: 'macos-钱包',
    icon: '👛',
    template: 'shoebox://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_calshow',
    name: 'macos-日历(calshow)',
    icon: '📅',
    template: 'calshow://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_ical',
    name: 'macos-日历(ical)',
    icon: '📆',
    template: 'ical://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_webcal',
    name: 'macos-日历订阅(webcal)',
    icon: '🗓️',
    template: 'webcal://{param}',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_shareddocuments',
    name: 'macos-文件',
    icon: '📁',
    template: 'shareddocuments://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_findmy',
    name: 'macos-查找',
    icon: '📍',
    template: 'findmy://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_stocks',
    name: 'macos-股市',
    icon: '📈',
    template: 'stocks://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_vedios',
    name: 'macos-视频',
    icon: '🎬',
    template: 'vedios://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_weather',
    name: 'macos-天气',
    icon: '🌤️',
    template: 'weather://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_addressbook',
    name: 'macos-通讯录',
    icon: '👥',
    template: 'addressbook://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_reminderkit',
    name: 'macos-提醒事项',
    icon: '✅',
    template: 'x-apple-reminderkit://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_applefeedback',
    name: 'macos-反馈助理',
    icon: '🛠️',
    template: 'applefeedback://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_mobilenotes',
    name: 'macos-备忘录',
    icon: '📝',
    template: 'mobilenotes://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_camera',
    name: 'macos-相机',
    icon: '📷',
    template: 'camera://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_photos_redirect',
    name: 'macos-照片(redirect)',
    icon: '🖼️',
    template: 'photos-redirect://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_photos',
    name: 'macos-照片',
    icon: '🌄',
    template: 'photos://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_music',
    name: 'macos-音乐',
    icon: '🎵',
    template: 'music://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_pcast',
    name: 'macos-播客',
    icon: '🎙️',
    template: 'pcast://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_map',
    name: 'macos-地图',
    icon: '🗺️',
    template: 'map://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_ibooks',
    name: 'macos-图书',
    icon: '📚',
    template: 'ibooks://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_facetime',
    name: 'macos-FaceTime',
    icon: '📹',
    template: 'facetime://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_freeform',
    name: 'macos-无边记',
    icon: '🧩',
    template: 'freeform://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_app_prefs',
    name: 'macos-设置(App-Prefs)',
    icon: '⚙️',
    template: 'App-Prefs:root',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_systempreferences',
    name: 'macos-设置(systempreferences)',
    icon: '🔧',
    template: 'x-apple.systempreferences://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_itms',
    name: 'macos-iTunes Store',
    icon: '🎞️',
    template: 'itms://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_itms_apps',
    name: 'macos-App Store',
    icon: '🛍️',
    template: 'itms-apps://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_x_web_search',
    name: 'macos-Safari(web-search)',
    icon: '🧭',
    template: 'x-web-search:///?{param}',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_x_safari_https',
    name: 'macos-Safari(https)',
    icon: '🌐',
    template: 'x-safari-https://',
    paramType: 'string',
  },
  {
    id: 'scheme_macos_shortcuts',
    name: 'macos-快捷指令',
    icon: '⚡',
    template: 'shortcuts://',
    paramType: 'string',
  },
  {
    id: 'scheme_weixin_scanqrcode',
    name: '微信-扫一扫',
    icon: '🟢',
    template: 'weixin://scanqrcode',
    paramType: 'string',
  },
  {
    id: 'scheme_weixin_widget_pay',
    name: '微信-付款码',
    icon: '💚',
    template: 'weixin://widget/pay',
    paramType: 'string',
  },
  {
    id: 'scheme_mqqapi_scan_qrcode',
    name: 'QQ国际版-扫一扫',
    icon: '🐧',
    template: 'mqqapi://qrcode/scan_qrcode?version=1&src_type=app',
    paramType: 'string',
  },
  {
    id: 'scheme_mqqapi_card_show_pslcard',
    name: 'QQ国际版-用户主页',
    icon: '🪪',
    template: 'mqqapi://card/show_pslcard?src_type=internal&version=1&uin={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_zhihu_codereader',
    name: '知乎-扫一扫',
    icon: '🔵',
    template: 'zhihu://codereader',
    paramType: 'string',
  },
  {
    id: 'scheme_zhihu_search',
    name: '知乎-搜索',
    icon: '🔎',
    template: 'zhihu://search?q={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_zhihu_question',
    name: '知乎-问题',
    icon: '❓',
    template: 'zhihu://question/{param}',
    paramType: 'string',
  },
  {
    id: 'scheme_xhs_search_recommend',
    name: '小红书-搜索页',
    icon: '📕',
    template: 'xhsdiscover://search/recommend',
    paramType: 'string',
  },
  {
    id: 'scheme_xhs_search_result',
    name: '小红书-搜索',
    icon: '🔍',
    template: 'xhsdiscover://search/result?keyword={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_xhs_scan',
    name: '小红书-扫一扫',
    icon: '📷',
    template: 'xhsdiscover://scan',
    paramType: 'string',
  },
  {
    id: 'scheme_xhs_item',
    name: '小红书-帖子',
    icon: '📝',
    template: 'xhsdiscover://item/{param}',
    paramType: 'string',
  },
  {
    id: 'scheme_xhs_user',
    name: '小红书-用户主页',
    icon: '👤',
    template: 'xhsdiscover://user/{param}',
    paramType: 'string',
  },
  {
    id: 'scheme_weibo_qrcode',
    name: '微博-扫一扫',
    icon: '🟥',
    template: 'weibo://qrcode',
    paramType: 'string',
  },
  {
    id: 'scheme_weibo_searchall',
    name: '微博-搜索',
    icon: '🔎',
    template: 'weibo://searchall?q={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_weibo_share',
    name: '微博-发微博',
    icon: '📣',
    template: 'weibo://share?content={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_sinaweibo_userinfo',
    name: '微博-用户主页',
    icon: '🙍',
    template: 'sinaweibo://userinfo?uid={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_wemeet',
    name: '腾讯会议',
    icon: '📹',
    template: 'wemeet://inmeeting?code={param}',
    paramType: 'number',
  },
  {
    id: 'scheme_mail',
    name: '邮件',
    icon: '✉️',
    template: 'mailto:{param}?subject={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_maps',
    name: '高德地图',
    icon: '🗺️',
    template: 'iosamap://path?sourceApplication=linkflow&dname={param}',
    paramType: 'string',
  },
  {
    id: 'scheme_script_local',
    name: '本地脚本',
    icon: '📜',
    template: '/absolute/path/to/your-script.sh',
    kind: 'script',
    paramType: 'string',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task_1',
    listId: 'list_today',
    title: '参加产品例会',
    completed: false,
    time: '10:30',
    actions: [{ schemeId: 'scheme_wemeet', params: ['123456789'] }],
  },
  {
    id: 'task_2',
    listId: 'list_work',
    title: '给客户发送周报',
    completed: false,
    date: '2026-02-20',
    actions: [{ schemeId: 'scheme_mail', params: ['team@example.com', 'LinkFlow 周报'] }],
  },
  {
    id: 'task_3',
    listId: 'list_life',
    title: '导航去健身房',
    completed: true,
    actions: [{ schemeId: 'scheme_maps', params: ['静安体育中心'] }],
  },
];
